language: node_js
node_js: stable
script:
- npm run test:lint
- polymer test --skip-plugin local
- npm run test:galen:sauce
addons:
  apt:
    packages:
      - oracle-java8-installer
  jwt:
    secure: MXlloSa+k+ma0yZEpXYtm0C6Y7/lvaxO2edWZEkUfByNzs+n1DL8O/dvqkQHXIBQkx/DHOCtPbCJDT5H2HBLzDUi0ttJT6YixVDIjdIUlMiuyHi8RdHeDfpRT4PIakEEFLxdhB5xC4usD4wstjKK0mINR6V2n36el0eE+9QPEvM=
before_install:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
- export PATH=$JAVA_HOME/bin:$PATH
env:
  global:
    SAUCE_USERNAME: Desire2Learn
